from typing import Protocol
from .entities import Team
from .value_objects import TeamCode


class TeamRepository(Protocol):
    async def get_by_id(self, team_id: int) -> Team | None: ...
    async def get_by_code(self, code: TeamCode) -> Team | None: ...
    async def save(self, team: Team) -> None: ...
    async def delete(self, team: Team) -> None: ...
