from typing import Protocol
from .entities import User
from .value_objects import Email, RawPassword


class UserRepository(Protocol):
    async def get_by_email(self, email: Email) -> User | None: ...
    async def save(self, user: User) -> None: ...
    async def get_by_id(self, user_id: int) -> User | None: ...
    async def delete(self, user: User) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: RawPassword) -> str: ...
    def verify(self, password: RawPassword, hashed: str) -> bool: ...
