from typing import Protocol
from .entities import Task


class TaskRepository(Protocol):
    async def get_by_id(self, task_id: int) -> Task | None: ...
    async def get_by_team(self, team_id: int) -> list[Task]: ...
    async def get_by_assignee(self, user_id: int) -> list[Task]: ...
    async def save(self, task: Task) -> None: ...
    async def delete(self, task: Task) -> None: ...
