"""add team_id to users

Revision ID: 62af665470ee
Revises: 87a916ebfca3
Create Date: 2026-07-02 15:17:10.076142

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "62af665470ee"
down_revision: Union[str, Sequence[str], None] = "87a916ebfca3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
