from typing import Protocol
from .entities import Evaluation


class EvaluationRepository(Protocol):
    async def get_by_task(self, task_id: int) -> list[Evaluation]: ...
    async def get_by_user(self, user_id: int) -> list[Evaluation]: ...
    async def save(self, evaluation: Evaluation) -> None: ...
